

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/jpashop
      username: sa
      password:
      driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
  batch:
    job:
      names: ${job.name:NONE}